/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:025ed2d0-8fa9-4419-8735-064d89728b87",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_0bNQBsQIZ",
    "aws_user_pools_web_client_id": "d2djgic0cl9oe7vnnhebrak8t",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mqhqx43dvzgbvo7mqaps7drlti.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
